name: reactive_{{originalPackageName.snakeCase()}}
description: Wrapper around {{originalPackageName.snakeCase()}} to use with reactive_forms.
version: 0.0.1
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_{{originalPackageName.snakeCase()}}
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
